# Basic Ubuntu and Docker setup Vagrantfile
#
# Weave Getting Started Guides
#

require 'fileutils'
require 'ipaddr'

Vagrant.require_version ">= 1.6.0"

VAGRANTFILE_API_VERSION = "2"
CONFIG = File.join(File.dirname(__FILE__), "config.rb")
SIMPLE_DOCKER_ALPINE = File.join(File.dirname(__FILE__), "Dockerfile-alpine")
ALPINE_REPOS= File.join(File.dirname(__FILE__), "repositories")
SIMPLE_DOCKER_UBUNTU = File.join(File.dirname(__FILE__), "Dockerfile-ubuntu")
PHP_EXAMPLE = File.join(File.dirname(__FILE__), "demo-src/index.php")
RSS_USAGE = File.join(File.dirname(__FILE__), "dockerRSSUsage.py")

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# Defaults for config options defined in CONFIG
#

$num_instances = 1
$instance_name_prefix = "weave-gs"
$share_home = false
$vm_gui = false
$vm_memory = 512
$vm_cpus = 1
$vm_starting_ip = "172.17.8.150"

if File.exist?(CONFIG)
    require CONFIG
end

$vm_ip = $vm_starting_ip

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.ssh.insert_key = true

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end

    (1..$num_instances).each do |i|
    
        config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
            config.vm.hostname = vm_name
            if  i == 1 
                config.vm.network "forwarded_port", guest: 80, host: 8080
            end        

            ip = IPAddr.new($vm_ip)
            $vm_ip = ip.succ.to_s
            config.vm.network "private_network", ip: $vm_ip
        end
    end

    config.vm.provider :virtualbox do |vb|
        vb.gui = $vm_gui
        vb.memory = $vm_memory
        vb.cpus = $vm_cpus
    end

    config.vm.provision "docker" do |d|
        d.pull_images "ubuntu"
        d.pull_images "nginx"
        d.pull_images "weaveworks/weave"
        d.pull_images "gliderlabs/alpine:edge"
    end

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        sudo curl -L git.io/weave -o /usr/local/bin/weave
        sudo chmod a+x /usr/local/bin/weave
        sudo apt-get install -y python-pip
        sudo pip install docker-py
    SHELL

    if File.exist?(SIMPLE_DOCKER_ALPINE)
        config.vm.provision "file", :source => "#{SIMPLE_DOCKER_ALPINE}", :destination => "/home/vagrant/Dockerfile-alpine"
        config.vm.provision "file", :source => "#{ALPINE_REPOS}", :destination => "/home/vagrant/repositories"
    end 
    
    if File.exist?(SIMPLE_DOCKER_UBUNTU)
        config.vm.provision "file", :source => "#{SIMPLE_DOCKER_UBUNTU}", :destination => "/home/vagrant/Dockerfile-ubuntu"
    end
    
    if File.exist?(RSS_USAGE)
        config.vm.provision "file", :source => "#{RSS_USAGE}", :destination => "/home/vagrant/dockerRSSUsage.py"
        config.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/dockerRSSUsage.py; chmod +x /home/vagrant/dockerRSSUsage.py" 
    end

    if File.exist?(PHP_EXAMPLE)
        config.vm.provision "shell", inline: "mkdir -p /home/vagrant/demo-src; chown -R vagrant:vagrant /home/vagrant/demo-src" 
        config.vm.provision "file", :source => "#{PHP_EXAMPLE}", :destination => "/home/vagrant/demo-src/index.php"
    end
end
